# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Expand column by splitting content with deliminter
#'@param src List. Data to be splitted. 
#'@param size integer. The size after splitted. Elements exceed the size will be discarded.
#'@param is_split logical. Indicate the corresponding column will be splitted or not.
#'@param delim char delimiter.
#'@details The size should not exceed the length after split or segment fault might occur.
#'@export
expand <- function(src, size, is_split, delim = ",") {
    .Call('WushUtility_expand', PACKAGE = 'WushUtility', src, size, is_split, delim)
}

#'@export
expandOrder <- function(size) {
    .Call('WushUtility_expandOrder', PACKAGE = 'WushUtility', size)
}

#'@export
ompBase64Decode <- function(src) {
    .Call('WushUtility_ompBase64Decode', PACKAGE = 'WushUtility', src)
}

#'@export
ompReadLines <- function(src, breakline = "\n") {
    .Call('WushUtility_ompReadLines', PACKAGE = 'WushUtility', src, breakline)
}

#'@export
ompSum.numeric <- function(src) {
    .Call('WushUtility_ompSum_numeric', PACKAGE = 'WushUtility', src)
}

#'@title Evaluate the size after split
#'@param src character. Strings to be splitted.
#'@param delim char. Delimiter. Only the first char will be used.
#'@return integer. The length of src splitted by delim.
#'@export
splitSize <- function(src, delim) {
    .Call('WushUtility_splitSize', PACKAGE = 'WushUtility', src, delim)
}

#'@export
splitToList.character <- function(src, size, delim) {
    .Call('WushUtility_splitToList_character', PACKAGE = 'WushUtility', src, size, delim)
}

#'@export
splitToList.factor <- function(src, size, delim) {
    .Call('WushUtility_splitToList_factor', PACKAGE = 'WushUtility', src, size, delim)
}

#'@export
syncSize <- function(src) {
    .Call('WushUtility_syncSize', PACKAGE = 'WushUtility', src)
}

