# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
ompSum.numeric <- function(src) {
    .Call('WushUtility_ompSum_numeric', PACKAGE = 'WushUtility', src)
}

#'@title Evaluate the size after split
#'@param src character. Strings to be splitted.
#'@param delim char. Delimiter. Only the first char will be used.
#'@return integer. The length of src splitted by delim.
#'@export
splitSize <- function(src, delim) {
    .Call('WushUtility_splitSize', PACKAGE = 'WushUtility', src, delim)
}

splitToList.character <- function(src, ncol, delim) {
    .Call('WushUtility_splitToList_character', PACKAGE = 'WushUtility', src, ncol, delim)
}

splitToList.factor <- function(src, ncol, delim) {
    .Call('WushUtility_splitToList_factor', PACKAGE = 'WushUtility', src, ncol, delim)
}

